// Tabler icon code points for the tutorial videos — the site's public subset
// (video/public/fonts/tabler-subset.woff2, copied from public/fonts; 52 icons,
// MIT). Regenerate from its CSS when the site's subset changes.
export const TI = {
  "arrow-left": 0xea19,
  "arrow-right": 0xea1f,
  "battery-3": 0xea31,
  "bell": 0xea35,
  "books": 0xeff2,
  "box": 0xea45,
  "brain": 0xf59f,
  "brand-facebook": 0xec1a,
  "brand-google": 0xec1f,
  "brand-instagram": 0xec20,
  "brand-messenger": 0xec71,
  "brand-whatsapp": 0xec74,
  "building": 0xea4f,
  "calendar-check": 0xf824,
  "chart-bar": 0xea59,
  "check": 0xea5e,
  "chevron-right": 0xea61,
  "circle-check": 0xea67,
  "clock": 0xea70,
  "clock-hour-4": 0xf319,
  "cpu": 0xef8e,
  "credit-card": 0xea84,
  "external-link": 0xea99,
  "help-circle": 0xf91d,
  "language": 0xebbe,
  "list": 0xeb6b,
  "lock": 0xeae2,
  "mail": 0xeae5,
  "map-pin": 0xeae8,
  "message-2": 0xeaec,
  "message-circle-2": 0xeaed,
  "messages": 0xeb6c,
  "moon": 0xeaf8,
  "package": 0xeaff,
  "pencil": 0xeb04,
  "phone": 0xeb09,
  "photo": 0xeb0a,
  "player-play-filled": 0xf691,
  "plug": 0xebd9,
  "plug-x": 0xf0a1,
  "rocket": 0xec45,
  "search": 0xeb1c,
  "shopping-bag": 0xf5f8,
  "shopping-cart": 0xeb25,
  "sparkles": 0xf6d7,
  "speakerphone": 0xed61,
  "sun": 0xeb30,
  "user": 0xeb4d,
  "wand": 0xebcb,
  "wifi": 0xeb52,
  "world": 0xeb54,
  "x": 0xeb55,
};
